### ISSUE TITLE
Do you know about CopperheadOS?

### ISSUE THREAD

**Issue by oldk1332** [hardenedlinux/armv7-nexus7-grsec#1]
https://copperhead.co/android

From https://copperhead.co/android/docs/technical_overview :

They have ported PAX/grsec to a few Nexus devices.

Do you know this project?  Recently on their twitter:

https://twitter.com/CopperheadOS/status/769146806609608704

```
Going to be considering keeping the majority of the sources for the
Nougat-based CopperheadOS internal until the work is properly funded.

So far, there haven't been external contributors to CopperheadOS.
We've definitely lost revenue to sustain the project due to it though.

Alternatively, the sources could remain available but under a
non-commercial usage license (i.e. not FOSS) until the project is funded.
```

**Comment by citypw** [comment]
Hi oldk1332, I know CopperheadOS. What their doing is awesome. But the goals between us is slightly different. CopperheadOS is trying build the secure ROM by following the latest version of AOSP and new Nexus devices. My goal is just focus on how to mitigate kernel exploit from those _popular_ malwares for those 0ld g00d Android devices( 3.4 mostly, some are 3.10). If I understand correctly, CopperheadOS for N5 is almost the same thing I did in the 1st place. Then I realized more work( PXN, prevent infoleak, etc) need to be done to prevent those wilding exploits.

I've seen their recent announcement. I'm supporter of COS since day one because the whole FLOSS community getting benefit from it. But technique is one thing, while how you make money( business model) is another. They did what they had to do to survive. Hope they can find fundings.

**Comment by oldk1332** [comment]
OK, cool.

They also said "so far, there haven't been external contributors to COS", do you guys have ideas that are not implemented in COS?  I think they'll be happy to know there are similar efforts.

I'm fine with their recent announcement, hope they get properly funded.

**Comment by citypw** [comment]
I'm sure COS guys know what I did last year. Some of my work sent to them in earlier April. The 1st priority of COS is build secure ROM for the latest version, which armv8.0 specifically. My work won't be helpful for that.

**Comment by oldk1332** [comment]
Thanks for reply.
