### ISSUE TITLE
How could I make test case for PXN

### ISSUE THREAD

**Issue by soh0ro0t** [hardenedlinux/armv7-nexus7-grsec#4]
Hi guys,
I a new comer for hardened linux and quite confused about PXN feature as you mentioned in READ.me of this repo. I get some material from well known site:
[Grsecurity-wiki](https://en.wikibooks.org/wiki/Grsecurity/Appendix/Grsecurity_and_PaX_Configuration_Options#Enforce_non-executable_kernel_pages)

It says that "This is the kernel land equivalent of PAGEEXEC and MPROTECT,
that is, enabling this option will make it harder to inject
and execute 'foreign' code in kernel memory itself", what does it mean?
and how would write  test case if I wanna test the hardened feature.

I will be grateful for any answers.

**Comment by citypw** [comment]
Hi, KERNEXEC does much more than what PXN can provide. You can use typical ret2usr example to test PXN on ARM as well as can do it on x86 w/ SMEP enabled. You might be interested:

https://github.com/hardenedlinux/grsecurity-101-tutorials/blob/master/kernel_mitigation.md#ret2usr-protection

I'm done w/ the maintainence for the newer kernel publicly two years ago. But patch is always welcome! I'm closing this issue since there's no tech issue. Thanks.
